// Code generated by MockGen. DO NOT EDIT.
// Source: srv/srvhttp/service.go

// Package mock_srvhttp is a generated GoMock package.
package mock_srvhttp

import (
	rsa "crypto/rsa"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetKeyID mocks base method
func (m *MockService) GetKeyID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeyID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetKeyID indicates an expected call of GetKeyID
func (mr *MockServiceMockRecorder) GetKeyID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeyID", reflect.TypeOf((*MockService)(nil).GetKeyID))
}

// GetPublicKey mocks base method
func (m *MockService) GetPublicKey() *rsa.PublicKey {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicKey")
	ret0, _ := ret[0].(*rsa.PublicKey)
	return ret0
}

// GetPublicKey indicates an expected call of GetPublicKey
func (mr *MockServiceMockRecorder) GetPublicKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicKey", reflect.TypeOf((*MockService)(nil).GetPublicKey))
}

// BuildServiceToken mocks base method
func (m *MockService) BuildServiceToken(idTokenStr string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildServiceToken", idTokenStr)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildServiceToken indicates an expected call of BuildServiceToken
func (mr *MockServiceMockRecorder) BuildServiceToken(idTokenStr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildServiceToken", reflect.TypeOf((*MockService)(nil).BuildServiceToken), idTokenStr)
}
