// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetServiceTokenRequest struct {
	IdToken              string   `protobuf:"bytes,1,opt,name=IdToken,proto3" json:"IdToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServiceTokenRequest) Reset()         { *m = GetServiceTokenRequest{} }
func (m *GetServiceTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GetServiceTokenRequest) ProtoMessage()    {}
func (*GetServiceTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{0}
}

func (m *GetServiceTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceTokenRequest.Unmarshal(m, b)
}
func (m *GetServiceTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceTokenRequest.Marshal(b, m, deterministic)
}
func (m *GetServiceTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceTokenRequest.Merge(m, src)
}
func (m *GetServiceTokenRequest) XXX_Size() int {
	return xxx_messageInfo_GetServiceTokenRequest.Size(m)
}
func (m *GetServiceTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceTokenRequest proto.InternalMessageInfo

func (m *GetServiceTokenRequest) GetIdToken() string {
	if m != nil {
		return m.IdToken
	}
	return ""
}

type GetServiceTokenResponse struct {
	ServiceToken         string   `protobuf:"bytes,1,opt,name=ServiceToken,proto3" json:"ServiceToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetServiceTokenResponse) Reset()         { *m = GetServiceTokenResponse{} }
func (m *GetServiceTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GetServiceTokenResponse) ProtoMessage()    {}
func (*GetServiceTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0b84a42fa06f626, []int{1}
}

func (m *GetServiceTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetServiceTokenResponse.Unmarshal(m, b)
}
func (m *GetServiceTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetServiceTokenResponse.Marshal(b, m, deterministic)
}
func (m *GetServiceTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetServiceTokenResponse.Merge(m, src)
}
func (m *GetServiceTokenResponse) XXX_Size() int {
	return xxx_messageInfo_GetServiceTokenResponse.Size(m)
}
func (m *GetServiceTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetServiceTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetServiceTokenResponse proto.InternalMessageInfo

func (m *GetServiceTokenResponse) GetServiceToken() string {
	if m != nil {
		return m.ServiceToken
	}
	return ""
}

func init() {
	proto.RegisterType((*GetServiceTokenRequest)(nil), "authorisationservice.GetServiceTokenRequest")
	proto.RegisterType((*GetServiceTokenResponse)(nil), "authorisationservice.GetServiceTokenResponse")
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626) }

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4e, 0x2d, 0x2a,
	0xcb, 0x4c, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x49, 0x2c, 0x2d, 0xc9, 0xc8,
	0x2f, 0xca, 0x2c, 0x4e, 0x2c, 0xc9, 0xcc, 0xcf, 0x83, 0xca, 0x29, 0x19, 0x71, 0x89, 0xb9, 0xa7,
	0x96, 0x04, 0x43, 0x78, 0x21, 0xf9, 0xd9, 0xa9, 0x79, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25,
	0x42, 0x12, 0x5c, 0xec, 0x9e, 0x29, 0x60, 0x11, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18,
	0x57, 0xc9, 0x96, 0x4b, 0x1c, 0x43, 0x4f, 0x71, 0x01, 0xc8, 0x4c, 0x21, 0x25, 0x2e, 0x1e, 0x64,
	0x71, 0xa8, 0x4e, 0x14, 0x31, 0xa3, 0x36, 0x46, 0x2e, 0x11, 0x47, 0x64, 0xb7, 0x40, 0x65, 0x85,
	0xf2, 0xb8, 0xf8, 0xd1, 0xcc, 0x15, 0xd2, 0xd1, 0xc3, 0xe6, 0x6a, 0x3d, 0xec, 0x4e, 0x96, 0xd2,
	0x25, 0x52, 0x35, 0xc4, 0xb1, 0x4e, 0xac, 0x51, 0xcc, 0x89, 0x05, 0x99, 0x49, 0x6c, 0xe0, 0xf0,
	0x31, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x8a, 0x0e, 0x9d, 0x25, 0x30, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthorisationServiceClient is the client API for AuthorisationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthorisationServiceClient interface {
	GetServiceToken(ctx context.Context, in *GetServiceTokenRequest, opts ...grpc.CallOption) (*GetServiceTokenResponse, error)
}

type authorisationServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthorisationServiceClient(cc *grpc.ClientConn) AuthorisationServiceClient {
	return &authorisationServiceClient{cc}
}

func (c *authorisationServiceClient) GetServiceToken(ctx context.Context, in *GetServiceTokenRequest, opts ...grpc.CallOption) (*GetServiceTokenResponse, error) {
	out := new(GetServiceTokenResponse)
	err := c.cc.Invoke(ctx, "/authorisationservice.AuthorisationService/GetServiceToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorisationServiceServer is the server API for AuthorisationService service.
type AuthorisationServiceServer interface {
	GetServiceToken(context.Context, *GetServiceTokenRequest) (*GetServiceTokenResponse, error)
}

// UnimplementedAuthorisationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAuthorisationServiceServer struct {
}

func (*UnimplementedAuthorisationServiceServer) GetServiceToken(ctx context.Context, req *GetServiceTokenRequest) (*GetServiceTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceToken not implemented")
}

func RegisterAuthorisationServiceServer(s *grpc.Server, srv AuthorisationServiceServer) {
	s.RegisterService(&_AuthorisationService_serviceDesc, srv)
}

func _AuthorisationService_GetServiceToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorisationServiceServer).GetServiceToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authorisationservice.AuthorisationService/GetServiceToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorisationServiceServer).GetServiceToken(ctx, req.(*GetServiceTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthorisationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authorisationservice.AuthorisationService",
	HandlerType: (*AuthorisationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceToken",
			Handler:    _AuthorisationService_GetServiceToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
